safe: True
port: 4002
base-url:    /

gems:
  - jekyll-sitemap

source:      .
destination: ./_site
plugins:     ._plugins

future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   blog/:title

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  input: GFM

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style


exclude: [
    CNAME,
    node_modules,
    validation-status.json,
    validation-report.json,
    gruntfile.js,
    package.json,
    Gemfile,
    Gemfile.lock,
    grunt,
    .git,
    source,
]

# Custom vars
current_version:  0.2.2
repo: https://github.com/underlost/underlost.github.io
site: http://tyler.codes/
author: Tyler Rilling
