port: 4002
base-url:    /

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

source:      ./source/site
destination: ./.publish
plugins_dir: ./source/site/_plugins

future:      true
lsi:         false
highlighter: true
markdown:    kramdown
permalink:   :title

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  input: GFM

exclude: [README.md, CHANGELOG.md, ]


# Site vars
current_version:  3.0.0
repo: https://github.com/underlost/tyler.codes
author: Tyler Rilling
title: Tyler.Codes
description: 'Tyler Rilling makes things on the internet.'
url: 'https://tyler.codes'

twitter:
  username: underlost
  card: summary

social:
  name: Tyler Rilling
  links:
    - https://twitter.com/underlost
    - https://github.com/underlost
    - https://keybase.io/underlost
    - https://instagram.com/underlost
