port: 4002
base-url:    /
url: 'https://tyler.codes'

plugins:
  - jekyll-sitemap

source:      ./source/site
destination: ./.publish
plugins_dir: ./source/site/_plugins

future:      true
lsi:         false
highlighter: true
markdown:    kramdown
permalink:   blog/:title

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  input: GFM

collections:
  projects:
    label: projects
    output: true
    relative_directory: portfolio/:slug
    directory: portfolio/:slug

  portfolio:
    label: portfolio
    output: true
    relative_directory: portfolio/:slug
    directory: portfolio/:slug

  misc:
    label: misc
    output: true
    relative_directory: portfolio/:slug
    directory: portfolio/:slug


exclude: [
  README.md,
  CHANGELOG.md
]

# Custom vars
current_version:  2.1.0
repo: https://github.com/underlost/tyler.codes
site: https://tyler.codes
author: Tyler Rilling
title: Tyler.Codes
